apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: devops-lab
  labels:
    app: nginx
spec:
  containers:
    - name: nginx
      image: nginx:stable
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 80
