name: day16
services:
  api:
    build:
      context: /home/yj/devops-labs/docker/day14/app
      dockerfile: Dockerfile
    environment:
      APP_NAME: devops-python-api-compose
      PORT: "8000"
    expose:
      - "8000"
    healthcheck:
      test:
        - CMD
        - python
        - -c
        - import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/health')
      timeout: 3s
      interval: 10s
      retries: 3
      start_period: 5s
    image: devops-python-api:compose
    networks:
      default: null
    restart: unless-stopped
    volumes:
      - type: volume
        source: api-data
        target: /data
        volume: {}
  nginx:
    depends_on:
      api:
        condition: service_healthy
        required: true
    image: nginx:stable
    networks:
      default: null
    ports:
      - mode: ingress
        target: 80
        published: "8094"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /home/yj/devops-labs/docker/day16/nginx/default.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
        bind: {}
networks:
  default:
    name: day16_default
volumes:
  api-data:
    name: day16_api-data
